// Package identity is the single source of truth for application identity.
//
// This file is GENERATED by the `setup` command. Do not edit by hand —
// re-run `setup` to change identity. All config/logging/database defaults
// and filesystem locations derive from the values below.
package identity

var (
	AppName    = "go-cli"        // human/app name
	ConfigName = "go-cli-config" // config file base name
	EnvPrefix  = "GOCLI"         // environment variable prefix
	DataDir    = ".go-cli"       // runtime data directory
	BinTrio    = "cli"           // binary prefix: cli, cli-config, cli-migration
)
